WITH TAB AS (SELECT CART_ID, GROUP_CONCAT(DISTINCT NAME) AS NAME
FROM CART_PRODUCTS
GROUP BY CART_ID
ORDER BY CART_ID)

SELECT DISTINCT A.CART_ID
FROM CART_PRODUCTS AS A
INNER JOIN
TAB AS N
ON A.CART_ID = N.CART_ID
WHERE N.NAME LIKE '%Milk%Yogurt%'
ORDER BY A.CART_ID