WITH REVIEW_COUNT AS 
(SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE, 
 COUNT(REVIEW_ID) AS CNT
 FROM REST_REVIEW
GROUP BY MEMBER_ID)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, 
DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM
MEMBER_PROFILE AS M
INNER JOIN
REST_REVIEW AS R
ON M.MEMBER_ID = R.MEMBER_ID
INNER JOIN
(SELECT MEMBER_ID FROM REVIEW_COUNT
WHERE CNT = (SELECT MAX(CNT) FROM REVIEW_COUNT)) AS A
ON A.MEMBER_ID = R.MEMBER_ID

ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC
