SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN
AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN
BOOK_SALES AS C
ON A.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.CATEGORY, A.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC