SELECT HISTORY_ID, ROUND(DAILY_FEE * 0.01 * (100-CASE WHEN
                                           DISCOUNT_RATE IS NULL THEN 0
                                          ELSE DISCOUNT_RATE END) * (DATEDIFF(END_DATE,START_DATE) + 1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
INNER JOIN
CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID
LEFT JOIN
CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON C.CAR_TYPE = A.CAR_TYPE AND
CASE WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >= 90
THEN '90일 이상'
WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >= 30
THEN '30일 이상'
WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >=7
THEN '7일 이상'END = C.DURATION_TYPE
WHERE A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, B.HISTORY_ID DESC