WITH RECURSIVE CTE AS
(SELECT ID, PARENT_ID, 1 AS DEPTH
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
UNION ALL
SELECT A.ID, A.PARENT_ID, C.DEPTH + 1
FROM ECOLI_DATA AS A
JOIN CTE AS C
ON C.ID = A.PARENT_ID)
SELECT ID FROM CTE
WHERE DEPTH = 3
ORDER BY ID ASC